(()=>{'use strict';
const KEY='asset-client-data-v1';
const seed={clients:[{id:'c1',name:'Clerici S.p.A.',code:'CLI-001',contact:'',email:''},{id:'c2',name:'Divisione Nord',code:'CLI-002',contact:'',email:''}],branches:[{id:'b1',name:'Brescia Est',code:'BR-001',city:'Brescia',clientId:'c1'},{id:'b2',name:'Milano Centrale',code:'BR-002',city:'Milano',clientId:'c1'}],devices:[{id:'d1',serial:'DEMO-0001',type:'Telefono IP',brand:'Cisco',model:'8841',status:'Assegnato',branchId:'b1',assignedTo:''},{id:'d2',serial:'DEMO-0002',type:'Telefono cordless',brand:'Cisco',model:'840',status:'Disponibile',branchId:'',assignedTo:''},{id:'d3',serial:'DEMO-0003',type:'Telefono IP',brand:'Cisco',model:'7811',status:'Guasto',branchId:'b2',assignedTo:''}]};
let db;try{db=JSON.parse(localStorage.getItem(KEY))||JSON.parse(JSON.stringify(seed))}catch{db=JSON.parse(JSON.stringify(seed))}
let page='dashboard',editId=null,q='';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cfg={clients:{label:'Clienti',one:'cliente',fields:[['name','Nome cliente','text',1],['code','Codice','text',1],['contact','Referente','text'],['email','Email','email']]},branches:{label:'Filiali',one:'filiale',fields:[['name','Nome filiale','text',1],['code','Codice','text',1],['city','Città','text',1],['clientId','Cliente','client',1]]},devices:{label:'Dispositivi',one:'dispositivo',fields:[['serial','Seriale / matricola','text',1],['type','Tipologia','select:Telefono IP|Telefono cordless|Smartphone|Router|Switch|Access point|PC|Altro',1],['brand','Marca','text'],['model','Modello','text',1],['status','Stato','select:Disponibile|Assegnato|Operativo|In consegna|In riparazione|Guasto|Dismesso',1],['branchId','Filiale','branch'],['assignedTo','Assegnato a','text']]}};
function persist(){localStorage.setItem(KEY,JSON.stringify(db))}
function getName(arr,id){return arr.find(x=>x.id===id)?.name||'—'}
function status(s){return s==='Disponibile'||s==='Operativo'?'ok':s==='Guasto'||s==='Dismesso'?'bad':s==='In riparazione'||s==='In consegna'?'warn':''}
function tableDevices(rows,actions=true){return '<div style="overflow:auto"><table><thead><tr><th>Seriale</th><th>Dispositivo</th><th>Filiale</th><th>Stato</th>'+(actions?'<th>Azioni</th>':'')+'</tr></thead><tbody>'+(rows.length?rows.map(d=>'<tr><td>'+esc(d.serial)+'</td><td>'+esc([d.brand,d.model].filter(Boolean).join(' '))+' · '+esc(d.type)+'</td><td>'+esc(getName(db.branches,d.branchId))+'</td><td><span class="badge '+status(d.status)+'">'+esc(d.status)+'</span></td>'+(actions?'<td><button data-edit="'+d.id+'">Modifica</button> <button data-del="'+d.id+'">Elimina</button></td>':'')+'</tr>').join(''):'<tr><td colspan="5">Nessun dispositivo trovato.</td></tr>')+'</tbody></table></div>'}
function listing(){let rows=db[page].filter(x=>Object.values(x).some(v=>String(v??'').toLowerCase().includes(q.toLowerCase())));if(page==='devices')return tableDevices(rows);let cols=page==='clients'?[['name','Cliente'],['code','Codice'],['contact','Referente'],['email','Email']]:[['name','Filiale'],['code','Codice'],['city','Città'],['clientId','Cliente']];return '<div style="overflow:auto"><table><thead><tr>'+cols.map(c=>'<th>'+c[1]+'</th>').join('')+'<th>Azioni</th></tr></thead><tbody>'+(rows.length?rows.map(x=>'<tr>'+cols.map(c=>'<td>'+esc(c[0]==='clientId'?getName(db.clients,x[c[0]]):x[c[0]]||'—')+'</td>').join('')+'<td><button data-edit="'+x.id+'">Modifica</button> <button data-del="'+x.id+'">Elimina</button></td></tr>').join(''):'<tr><td colspan="5">Nessun risultato. Aggiungi un record con il pulsante in alto.</td></tr>')+'</tbody></table></div>'}
function dashboard(){let assigned=db.devices.filter(x=>['Assegnato','Operativo'].includes(x.status)).length,broken=db.devices.filter(x=>x.status==='Guasto').length,available=db.devices.filter(x=>x.status==='Disponibile').length;return '<section class="hero"><div><span class="badge">MVP 0.3.0</span><h3>Gestione centralizzata degli asset</h3><p>Gestisci clienti, filiali e dispositivi. I dati iniziali sono dimostrativi: puoi modificarli o cancellarli.</p></div><div class="hero-card"><b>Stato inventario</b><p>'+db.devices.length+' dispositivi registrati</p><p>'+available+' disponibili · '+broken+' guasti</p></div></section><section class="stats"><article class="card"><h4>Clienti</h4><div class="metric">'+db.clients.length+'</div></article><article class="card"><h4>Filiali</h4><div class="metric">'+db.branches.length+'</div></article><article class="card"><h4>Dispositivi assegnati</h4><div class="metric">'+assigned+'</div></article></section><section class="card"><h4>Dispositivi recenti</h4>'+tableDevices(db.devices.slice(-5).reverse(),false)+'</section><p class="footer-note">Questa versione salva i dati nel browser corrente (localStorage). Non è un database condiviso e non include login o backup centralizzato.</p>'}
function render(){document.querySelectorAll('.nav a').forEach(a=>{a.classList.toggle('active',({'dashboard':'Dashboard','clients':'Clienti','branches':'Filiali','devices':'Dispositivi'})[page]===a.querySelector('span')?.textContent)});const labels={dashboard:'Dashboard',clients:'Clienti',branches:'Filiali',devices:'Dispositivi'};$('.title h2').textContent=labels[page];$('.title p').textContent=page==='dashboard'?'Panoramica dell’inventario aziendale.':'Gestione anagrafiche e inventario.';const wrap=$('.wrap');if(page==='dashboard'){wrap.innerHTML=dashboard()}else{wrap.innerHTML='<section class="card"><div style="display:flex;gap:12px;justify-content:space-between;align-items:center;flex-wrap:wrap"><h4 style="margin:0">'+cfg[page].label+' ('+db[page].length+')</h4><input id="assetSearch" type="search" placeholder="Cerca..." value="'+esc(q)+'" style="padding:10px;border:1px solid var(--border);border-radius:10px"></div><div id="assetRows">'+listing()+'</div></section>'}const originalNew=$('.actions .btn-primary');if(originalNew)originalNew.style.display='none';const old=$('#assetNew');if(old)old.remove();const b=document.createElement('button');b.id='assetNew';b.className='btn-primary';b.textContent='+ Nuovo '+(page==='dashboard'?'dispositivo':cfg[page].one);$('.actions').append(b);b.onclick=()=>{if(page==='dashboard')page='devices';openForm()};const exportBtn=[...document.querySelectorAll('.actions button')].find(x=>x.textContent.trim()==='Esporta');if(exportBtn)exportBtn.onclick=exportCsv}
function openForm(id){editId=id||null;const item=id?db[page].find(x=>x.id===id):{};const fields=cfg[page].fields;let html=fields.map(([k,label,type,req])=>{let val=item[k]||'',required=req?'required':'';if(type==='client'||type==='branch'){let arr=type==='client'?db.clients:db.branches;return '<label>'+label+(req?' *':'')+'<select name="'+k+'" '+required+'><option value="">— Non assegnato —</option>'+arr.map(o=>'<option value="'+o.id+'" '+(val===o.id?'selected':'')+'>'+esc(o.name)+'</option>').join('')+'</select></label>'}if(type.startsWith('select:'))return '<label>'+label+(req?' *':'')+'<select name="'+k+'" '+required+'>'+type.slice(7).split('|').map(o=>'<option '+(val===o?'selected':'')+'>'+o+'</option>').join('')+'</select></label>';return '<label>'+label+(req?' *':'')+'<input name="'+k+'" type="'+type+'" value="'+esc(val)+'" '+required+'></label>'}).join('');let modal=$('#assetModal');if(!modal){modal=document.createElement('div');modal.id='assetModal';modal.style.cssText='position:fixed;inset:0;background:#0008;display:grid;place-items:center;padding:16px;z-index:99';document.body.append(modal)}modal.innerHTML='<form style="background:var(--surface);color:var(--text);padding:24px;border-radius:18px;width:min(580px,100%);max-height:90vh;overflow:auto;display:grid;gap:14px" id="assetForm"><h2 style="margin:0">'+(id?'Modifica ':'Nuovo ')+cfg[page].one+'</h2><div class="asset-fields">'+html+'</div><div style="display:flex;justify-content:flex-end;gap:8px"><button type="button" id="assetCancel">Annulla</button><button class="btn-primary" type="submit">Salva</button></div></form>';const style=document.createElement('style');style.textContent='.asset-fields{display:grid;grid-template-columns:1fr 1fr;gap:12px}.asset-fields label{display:grid;gap:6px;font-size:.9rem}.asset-fields input,.asset-fields select{padding:10px;border:1px solid var(--border);border-radius:8px;background:var(--bg);color:var(--text);min-width:0}@media(max-width:600px){.asset-fields{grid-template-columns:1fr}}';modal.append(style);$('#assetCancel').onclick=()=>modal.remove();modal.onclick=e=>{if(e.target===modal)modal.remove()};$('#assetForm').onsubmit=e=>{e.preventDefault();let obj={};for(const [k] of fields)obj[k]=new FormData(e.target).get(k)||'';if(page==='devices'&&db.devices.some(d=>d.serial.toLowerCase()===String(obj.serial).toLowerCase()&&d.id!==editId)){alert('Seriale già presente.');return}if(editId)Object.assign(db[page].find(x=>x.id===editId),obj);else db[page].push({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),...obj});persist();modal.remove();render()}}
function remove(id){if(!confirm('Confermi l’eliminazione?'))return;db[page]=db[page].filter(x=>x.id!==id);if(page==='clients'){let ids=new Set(db.clients.map(x=>x.id));db.branches=db.branches.filter(x=>ids.has(x.clientId))}if(page==='branches')db.devices.forEach(x=>{if(x.branchId===id)x.branchId='' });persist();render()}
function exportCsv(){let rows=db[page];if(!rows.length){alert('Nessun dato da esportare');return}let keys=Object.keys(rows[0]),csv=[keys.join(';'),...rows.map(x=>keys.map(k=>'"'+String(k==='clientId'?getName(db.clients,x[k]):k==='branchId'?getName(db.branches,x[k]):x[k]??'').replace(/"/g,'""')+'"').join(';'))].join('\r\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));a.download=page+'-asset-client.csv';a.click();URL.revokeObjectURL(a.href)}
document.querySelectorAll('.nav a').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();let t=a.querySelector('span')?.textContent;page=({'Dashboard':'dashboard','Clienti':'clients','Filiali':'branches','Dispositivi':'devices'})[t]||'dashboard';q='';render()}));
$('.wrap').addEventListener('click',e=>{let ed=e.target.closest('[data-edit]'),del=e.target.closest('[data-del]'),go=e.target.closest('[data-goto]');if(ed)openForm(ed.dataset.edit);if(del)remove(del.dataset.del);if(go){page=go.dataset.goto;render()}});
$('.wrap').addEventListener('input',e=>{if(e.target.id==='assetSearch'){q=e.target.value;$('#assetRows').innerHTML=listing()}});
const theme=$('#themeToggle');if(theme)theme.addEventListener('click',()=>{let t=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=t;localStorage.setItem('asset-client-theme',t)});let saved=localStorage.getItem('asset-client-theme');if(saved)document.documentElement.dataset.theme=saved;
if(!localStorage.getItem(KEY))persist();render();
})();